# -*- coding: utf-8 -*-
"""Engenharia de Dados III - Construindo Datamart com Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjDaVAzUuNwYsxJ8rZ7abJzkrVKHFe73
"""

!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd

# Define o nome EXATO do arquivo que existe dentro do dataset no Kaggle
file_path = "pip.csv"

# Carrega o dataset diretamente do Kaggle
df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,
                            "isaaclopgu/share-of-population-living-in-extreme-poverty",
                            file_path,)

print("Primeiros 5 registros:")
display(df.head())

# Criar dimensão País/Região
dim_country = df[['region_name', 'region_code', 'country_name', 'country_code']].drop_duplicates().reset_index(drop=True)
dim_country['country_id'] = dim_country.index + 1
dim_country = dim_country[['country_id', 'region_name', 'region_code', 'country_name', 'country_code']]

print("Dimensão País/Região:")
print(dim_country.head())

# Dimensão Ano
dim_year = df[['reporting_year', 'reporting_level', 'survey_year', 'survey_acronym', 'survey_coverage']].drop_duplicates().reset_index(drop=True)
dim_year['year_id'] = dim_year.index + 1
dim_year = dim_year[['year_id', 'reporting_year', 'reporting_level', 'survey_year', 'survey_acronym', 'survey_coverage']]

print("Dimensão Ano / Reportagem:")
print(dim_year.head())

# Dimensão Welfare / Linha de pobreza
dim_welfare = df[['welfare_type', 'poverty_line', 'distribution_type', 'estimation_type', 'estimate_type']].drop_duplicates().reset_index(drop=True)
dim_welfare['welfare_id'] = dim_welfare.index + 1
dim_welfare = dim_welfare[['welfare_id', 'welfare_type', 'poverty_line', 'distribution_type', 'estimation_type', 'estimate_type']]

print("Dimensão Welfare / Linha de pobreza:")
print(dim_welfare.head())

# Dimensão Comparabilidade
dim_comparability = df[['survey_comparability', 'comparable_spell']].drop_duplicates().reset_index(drop=True)
dim_comparability['comparability_id'] = dim_comparability.index + 1
dim_comparability = dim_comparability[['comparability_id', 'survey_comparability', 'comparable_spell']]

print("Dimensão Comparabilidade:")
print(dim_comparability.head())

# Tabela Fato Pobreza
fact_poverty = df.merge(dim_country, on=['country_name', 'country_code', 'region_name', 'region_code']) \
                 .merge(dim_year, on='reporting_year') \
                 .merge(dim_welfare, on=['welfare_type','poverty_line','distribution_type','estimation_type','estimate_type']) \
                 .merge(dim_comparability, on=['survey_comparability','comparable_spell'])

fact_poverty = fact_poverty[['country_id', 'year_id', 'welfare_id', 'comparability_id',
                             'headcount','poverty_gap','poverty_severity','watts','mean','median','gini']]

print("Dimensão País/Região:")
print(dim_country.head())
print("\nDimensão Ano / Reportagem:")
print(dim_year.head())
print("\nDimensão Bem-estar / Linha de pobreza:")
print(dim_welfare.head())
print("\nFato Pobreza:")
print(fact_poverty.head())

# 5. Gravar tudo no datamart.db
# -----------------------------
def salvar_datamart(df_dim_country, df_dim_year, df_dim_welfare, df_dim_comparability, df_fact_poverty):
    conn_dm = sqlite3.connect(DATAMART_DB)

    # Salva dados no data mart, substituindo se as tabelas já existirem
    df_dim_country.to_sql("dim_country", conn_dm, if_exists="replace", index=False)
    df_dim_year.to_sql("dim_year", conn_dm, if_exists="replace", index=False)
    df_dim_welfare.to_sql("dim_welfare", conn_dm, if_exists="replace", index=False)
    df_dim_comparability.to_sql("dim_comparability", conn_dm, if_exists="replace", index=False)
    df_fact_poverty.to_sql("fact_poverty", conn_dm, if_exists="replace", index=False)

    conn_dm.close()

# Importar sqlite3
import sqlite3

# Definir o nome do banco de dados do datamart
DATAMART_DB = "/content/drive/MyDrive/POSGRADUACAO/datamart.db"

print("Salvando no datamart...")
salvar_datamart(dim_country, dim_year, dim_welfare, dim_comparability, fact_poverty)
print(f"Datamart gerado em {DATAMART_DB}")